source "http://rubygems.org"

gemspec

group :development, :test do
  gem 'rspec'
  unless ENV['TRAVIS']
    gem 'simplecov'
    gem 'pry'
    gem 'pry-nav'
  end
end

group :development do
  gem 'yard', "~> 0.8.4.1"
  gem 'rdoc'
end

gem 'abc-core', :path => '../'
