source "http://rubygems.org"

gemspec

group :development, :test do
  gem 'rspec'
  unless ENV['TRAVIS']
    gem 'simplecov'
    gem 'guard-shell'
    gem 'rb-fsevent', '~> 0.9', :platform => :ruby
  end
end

group :development do
  gem 'yard', "~> 0.8.4.1"
  gem 'rdoc'
  gem 'kramdown'
end

gem 'abc', :path => '../'
