source "http://rubygems.org"

gemspec

git 'git://github.com/rails/rails.git' do
  gem 'railties'
  gem 'actionpack'
  gem 'activemodel'
end

group :test do
  gem 'rspec'
  gem 'rspec-rails', :require => false
  unless ENV['TRAVIS']
    gem 'simplecov'
  end
  gem 'capybara'
  platforms :jruby do
    gem 'activerecord-jdbcsqlite3-adapter'
    gem 'jruby-openssl'
  end

  platforms :ruby do
    gem 'sqlite3'
  end
end

group :development, :test do
  gem 'combustion', github: 'pat/combustion'
  unless ENV['TRAVIS']
    gem 'pry'
    gem 'pry-nav'
    gem 'guard-shell'
    gem 'rb-fsevent', '~> 0.9', :platform => :ruby
  end
end

group :development do
  gem 'yard', "~> 0.8.4.1"
  gem 'rdoc'
  gem 'kramdown'
end

gem 'abc-core', :path => '../../core'
gem 'abc-adapters', :path => '../../adapters'
