source "http://rubygems.org"

gemspec

git 'git://github.com/rails/rails.git' do
  gem 'railties'
  gem 'actionpack'
  gem 'activemodel'
end

group :test do
  gem 'rspec'
  gem 'rspec-rails', :require => false
  unless ENV['TRAVIS']
    gem 'simplecov'
  end
  gem 'capybara', github: 'knewter/capybara', branch: 'rails4-gem-version-fix'
  platforms :jruby do
    gem 'activerecord-jdbcsqlite3-adapter'
  end

  platforms :ruby do
    gem 'sqlite3'
  end
end

group :development, :test do
  gem 'combustion', github: 'knewter/combustion', branch: 'rails4-gem-version-fix'
  unless ENV['TRAVIS']
    gem 'pry'
    gem 'pry-nav'
    gem 'guard-shell'
    gem 'rb-fsevent', '~> 0.9', :platform => :ruby
  end
end

group :assets do
  gem 'sprockets-rails', github: 'rails/sprockets-rails'
  gem 'sass-rails',   github: 'rails/sass-rails'
  gem 'coffee-rails', github: 'rails/coffee-rails'

  gem 'uglifier', '>= 1.0.3'
end

gem 'haml', github: 'haml/haml', branch: 'stable'
gem 'haml-rails', github: 'indirect/haml-rails'

group :development do
  gem 'yard', "~> 0.8.4.1"
  gem 'rdoc'
  gem 'kramdown'
end

gem 'afterburner', :github => 'grounded/afterburner'
gem 'abc', :path => '../../'
gem 'abc-core', :path => '../../core'
gem 'abc-adapters', :path => '../../adapters'
gem 'afterburner', :github => 'grounded/afterburner'

gem "bourbon", "~> 3.1.1"
gem "neat", "~> 1.2.0"
