#!/usr/bin/env rake
# Add your own tasks in files placed in lib/tasks ending in .rake,
# for example lib/tasks/capistrano.rake, and they will automatically be available to Rake.

require 'rubygems'
require 'bundler/setup'

Bundler.require :default, :development, :test

Combustion.initialize! :action_view, :active_model, :action_controller
Combustion::Application.load_tasks
